FROM public.ecr.aws/docker/library/debian:bookworm-slim

# Enable 32-bit architecture for IOL 15.x binaries
RUN dpkg --add-architecture i386

# Install dependencies (including 32-bit libs for IOL 15.x and python3)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    iproute2 \
    iputils-ping \
    net-tools \
    sudo \
    curl \
    ca-certificates \
    gnupg \
    python3 \
    libc6-i386 \
    lib32z1 \
    lib32gcc-s1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Add containerlab gemfury for custom IOUYAP
RUN echo "deb [trusted=yes] https://netdevops.fury.site/apt/ /" | \
    sudo tee -a /etc/apt/sources.list.d/netdevops.list

# Update and install IOUYAP
RUN apt-get update && \
    apt-get install -y iouyap && \
    rm -rf /var/lib/apt/lists/*

# Copy scripts
COPY gen_license.py /gen_license.py
RUN chmod +x /gen_license.py
COPY iou_import /iou_import
RUN chmod +x /iou_import

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set working directory
WORKDIR /iol

# Add the IOL image and config files
COPY *.bin /iol/iol.bin

# Make the IOL image executable
RUN chmod +x /iol/iol.bin

ENTRYPOINT ["/entrypoint.sh"]
